# Generated by Django 3.1.2 on 2020-10-04 19:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201003_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Новость'),
        ),
    ]
