# Generated by Django 3.1.2 on 2020-10-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201010_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок тега')),
            ],
            options={
                'verbose_name': 'Теги',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='news',
            field=models.ManyToManyField(blank=True, related_name='news_tags', to='news.Tag', verbose_name='Теги'),
        ),
    ]
