# Generated by Django 3.1.2 on 2020-10-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201010_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок тега'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок тега'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_uk',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок тега'),
        ),
    ]
