# Generated by Django 3.1.2 on 2020-10-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20201010_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_slug',
            field=models.CharField(max_length=2000, null=True, verbose_name='ССылка на видео'),
        ),
    ]
