# Generated by Django 3.1.2 on 2020-10-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video_slug',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='ССылка на видео'),
        ),
    ]
