# Generated by Django 3.1.2 on 2020-10-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20201011_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title_en',
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
    ]
