# Generated by Django 3.1.2 on 2020-10-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20201017_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video_slug',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
