# Generated by Django 3.1.2 on 2020-10-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20201018_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
    ]
