# Generated by Django 3.1.2 on 2020-10-02 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('pilga_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_image', to='pilga_project.slider')),
            ],
            options={
                'verbose_name': 'Изображения слайдера',
                'verbose_name_plural': 'Изображения слайдера',
            },
        ),
    ]
