# Generated by Django 3.1.2 on 2020-10-02 21:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0002_auto_20201003_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=2048, null=True, verbose_name='Текст для слайдера'),
        ),
    ]
