# Generated by Django 3.1.2 on 2020-10-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0005_auto_20201004_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название льготы/субсидии')),
            ],
            options={
                'verbose_name': 'Льгота',
                'verbose_name_plural': 'Льготы',
            },
        ),
        migrations.CreateModel(
            name='PrivilegeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_type', to='pilga_project.privilege', verbose_name='Тип льготы/субсидии')),
            ],
            options={
                'verbose_name': 'Тип льготы/субсидии',
                'verbose_name_plural': 'Тип льготы/субсидии',
            },
        ),
        migrations.CreateModel(
            name='Group2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=500, null=True, verbose_name='Группа льгот/субсидий (уровень 2)')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_group2', to='pilga_project.privilege', verbose_name='Группа льгот/субсидий (уровень 2)')),
            ],
            options={
                'verbose_name': 'Группа льгот/субсидий (уровень 2)',
                'verbose_name_plural': 'Группа льгот/субсидий (уровень 2)',
            },
        ),
        migrations.CreateModel(
            name='Group1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=500, null=True, verbose_name='Группа льгот/субсидий (уровень 1)')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_group1', to='pilga_project.privilege', verbose_name='Группа льгот/субсидий (уровень 1)')),
            ],
            options={
                'verbose_name': 'Группа льгот/субсидий (уровень 1)',
                'verbose_name_plural': 'Группа льгот/субсидий (уровень 1)',
            },
        ),
    ]
