# Generated by Django 3.1.2 on 2020-10-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0006_group1_group2_privilege_privilegetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='group1',
            name='group_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Группа льгот/субсидий (уровень 1)'),
        ),
        migrations.AddField(
            model_name='group1',
            name='group_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Группа льгот/субсидий (уровень 1)'),
        ),
        migrations.AddField(
            model_name='group1',
            name='group_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Группа льгот/субсидий (уровень 1)'),
        ),
        migrations.AddField(
            model_name='group2',
            name='group_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Группа льгот/субсидий (уровень 2)'),
        ),
        migrations.AddField(
            model_name='group2',
            name='group_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Группа льгот/субсидий (уровень 2)'),
        ),
        migrations.AddField(
            model_name='group2',
            name='group_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Группа льгот/субсидий (уровень 2)'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='title_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название льготы/субсидии'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='title_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название льготы/субсидии'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='title_uk',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название льготы/субсидии'),
        ),
        migrations.AddField(
            model_name='privilegetype',
            name='type_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='privilegetype',
            name='type_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='privilegetype',
            name='type_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип'),
        ),
    ]
