# Generated by Django 3.1.2 on 2020-10-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0007_auto_20201005_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group1',
            name='privilege',
        ),
        migrations.RemoveField(
            model_name='group2',
            name='privilege',
        ),
        migrations.RemoveField(
            model_name='privilegetype',
            name='privilege',
        ),
        migrations.AddField(
            model_name='privilege',
            name='group1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_group1', to='pilga_project.group1', verbose_name='Группа льгот/субсидий (уровень 1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilege',
            name='group2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_group2', to='pilga_project.group2', verbose_name='Группа льгот/субсидий (уровень 2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilege',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_type', to='pilga_project.privilegetype'),
            preserve_default=False,
        ),
    ]
