# Generated by Django 3.1.2 on 2020-10-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0008_auto_20201005_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(blank=True, max_length=500, null=True, verbose_name='Орган рассмотрения выдачи льготы/субсидии')),
            ],
            options={
                'verbose_name': 'Орган рассмотрения выдачи льготы/субсидии',
                'verbose_name_plural': 'Орган рассмотрения выдачи льготы/субсидии',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Тип нормативного документа',
                'verbose_name_plural': 'Тип нормативного документа',
            },
        ),
        migrations.CreateModel(
            name='IssuedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued', models.CharField(blank=True, max_length=500, null=True, verbose_name='Кем выдан')),
            ],
            options={
                'verbose_name': 'Кем выдан',
                'verbose_name_plural': 'Кем выдан',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=500, null=True, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регион',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_document', models.CharField(blank=True, max_length=500, null=True, verbose_name='Требуемые документы')),
            ],
            options={
                'verbose_name': 'Требуемые документы',
                'verbose_name_plural': 'Требуемые документы',
            },
        ),
        migrations.AddField(
            model_name='privilege',
            name='annual_revision',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ежегодный пересмотр (Да/Нет)'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата нормативного документа'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='duration_end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок действия льготоы/субсидии до'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='duration_start',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок действия льготы/субсидии от'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='national',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Общенациональный (Да/Нет)'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='number',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номер нормативного документа'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='period_end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Период выплаты до'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='period_revision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Период/Месяц пересмотра'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='period_start',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Период выплаты с'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='single_pay',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Одноразовая выплата (Да/Нет)'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='slug',
            field=models.SlugField(default=1, max_length=1000, verbose_name='WEB Ссылка на официальный источник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilege',
            name='value',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Сумма или значение льготы/ субсидии'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_agency', to='pilga_project.agency', verbose_name='Орган рассмотрения выдачи льготы/субсидии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilege',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_document_type', to='pilga_project.region', verbose_name='Тип нормативного документа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilege',
            name='issued',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_issued', to='pilga_project.issuedby', verbose_name='Кем выдан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilege',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_region', to='pilga_project.region', verbose_name='Регион'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilege',
            name='required_document',
            field=models.ManyToManyField(related_name='privilege_required_document', to='pilga_project.RequiredDocument', verbose_name='Требуемые документы'),
        ),
    ]
