# Generated by Django 3.1.2 on 2020-10-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0009_auto_20201005_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Орган рассмотрения выдачи льготы/субсидии'),
        ),
        migrations.AddField(
            model_name='agency',
            name='agency_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Орган рассмотрения выдачи льготы/субсидии'),
        ),
        migrations.AddField(
            model_name='agency',
            name='agency_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Орган рассмотрения выдачи льготы/субсидии'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='document_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='document_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='document_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='issuedby',
            name='issued_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='issuedby',
            name='issued_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='issuedby',
            name='issued_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='required_document_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Требуемые документы'),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='required_document_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Требуемые документы'),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='required_document_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Требуемые документы'),
        ),
    ]
