# Generated by Django 3.1.2 on 2020-10-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0013_auto_20201006_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='WEB Ссылка на официальный источник'),
        ),
    ]
