# Generated by Django 3.1.2 on 2020-10-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0014_auto_20201006_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_agency', to='pilga_project.agency', verbose_name='Орган рассмотрения выдачи льготы/субсидии'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_document_type', to='pilga_project.documenttype', verbose_name='Тип нормативного документа'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='group1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_group1', to='pilga_project.group1', verbose_name='Группа льгот/субсидий (уровень 1)'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='group2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_group2', to='pilga_project.group2', verbose_name='Группа льгот/субсидий (уровень 2)'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='issued',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_issued', to='pilga_project.issuedby', verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='privilege_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_type', to='pilga_project.privilegetype'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_region', to='pilga_project.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='required_document',
            field=models.ManyToManyField(blank=True, null=True, related_name='privilege_required_document', to='pilga_project.RequiredDocument', verbose_name='Требуемые документы'),
        ),
    ]
