# Generated by Django 3.1.2 on 2020-10-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0015_auto_20201006_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='required_document',
            field=models.ManyToManyField(blank=True, related_name='privilege_required_document', to='pilga_project.RequiredDocument', verbose_name='Требуемые документы'),
        ),
    ]
