# Generated by Django 3.1.2 on 2020-10-07 21:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0016_auto_20201006_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
