# Generated by Django 3.1.2 on 2020-10-08 19:51

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('pilga_project', '0017_privilege_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подгруппа льгот/субсидий (уровень 2)')),
                ('group_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подгруппа льгот/субсидий (уровень 2)')),
                ('group_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подгруппа льгот/субсидий (уровень 2)')),
                ('group_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подгруппа льгот/субсидий (уровень 2)')),
            ],
            options={
                'verbose_name': 'Группа льгот/субсидий (уровень 2)',
                'verbose_name_plural': 'Группа льгот/субсидий (уровень 2)',
            },
        ),
        migrations.RenameModel(
            old_name='Group1',
            new_name='Group',
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='group1',
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='group2',
        ),
        migrations.AddField(
            model_name='agency',
            name='activity',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Деятельность'),
        ),
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='agency',
            name='building',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Учреждение'),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контакты тел.'),
        ),
        migrations.AddField(
            model_name='agency',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Департамент'),
        ),
        migrations.AddField(
            model_name='agency',
            name='geo_lat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='agency',
            name='geo_long',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='долгота'),
        ),
        migrations.AddField(
            model_name='agency',
            name='image',
            field=filer.fields.image.FilerImageField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agency_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='work_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_group', to='pilga_project.group', verbose_name='Группа льгот/субсидий (уровень 1)'),
        ),
        migrations.DeleteModel(
            name='Group2',
        ),
        migrations.AddField(
            model_name='privilege',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_subgroup', to='pilga_project.subgroup', verbose_name='Группа льгот/субсидий (уровень 2)'),
        ),
    ]
