# Generated by Django 3.1.2 on 2020-10-10 19:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0019_auto_20201008_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='О проекте')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Оптисание проекта')),
            ],
            options={
                'verbose_name': 'О проекте',
                'verbose_name_plural': 'О проекте',
            },
        ),
    ]
