# Generated by Django 3.1.2 on 2020-10-10 19:58

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('pilga_project', '0020_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Оптисание проекта'),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Оптисание проекта'),
        ),
        migrations.AddField(
            model_name='about',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Оптисание проекта'),
        ),
        migrations.AddField(
            model_name='about',
            name='geo_lat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='about',
            name='geo_long',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='долгота'),
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=filer.fields.image.FilerImageField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='about_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='О проекте'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='О проекте'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uk',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='О проекте'),
        ),
    ]
