# Generated by Django 3.1.2 on 2020-10-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilga_project', '0023_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='agency_en',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='document_en',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_en',
        ),
        migrations.RemoveField(
            model_name='issuedby',
            name='issued_en',
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='privilegetype',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_en',
        ),
        migrations.RemoveField(
            model_name='requireddocument',
            name='required_document_en',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='group_en',
        ),
    ]
